const ICONS = {
  ADD: "lucide:plus",
  BRUSH: "lucide:brush",
  CLOSE: "lucide:x",
  DASHBOARD: "lucide:layout-dashboard",
  DELETE: "lucide:trash-2",
  DOWNLOAD: "lucide:download",
  EDIT: "lucide:square-pen",
  ERROR: "lucide:circle-x",
  FOLDER: "lucide:folder",
  FROWN: "lucide:frown",
  HOME: "lucide:house",
  LOADING: "svg-spinners:ring-resize",
  LOCK: "lucide:lock",
  REFRESH: "lucide:refresh-cw",
  SEARCH: "lucide:search",
  SORT_DATE_ASC: "lucide:arrow-up-narrow-wide",
  SORT_DATE_DESC: "lucide:arrow-down-narrow-wide",
  SORT_NAME_ASC: "lucide:arrow-up-a-z",
  SORT_NAME_DESC: "lucide:arrow-down-a-z",
  SUBMIT: "lucide:check",
  SUCCESS: "lucide:circle-check",
  UPLOAD: "lucide:upload",
  USER: "lucide:user",
  USERS: "lucide:users",
  USER_COG: "lucide:user-cog",
  WARNING: "lucide:triangle-alert",
};

export { ICONS };
